customhost = "employee.cfbxja6pcmsd.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "joshuahorshenyang-employee"
customregion = "us-east-1a"
